goldfirere/singletons

- singletons.cabal
At least since https://github.com/goldfirere/singletons/pull/125, singletons 2.x no longer compiles with 7.8 but the current lower bound for `base` still results in picking a build plan with 7.8 and singletons 2.x which is doomed to fail. Hence I hereby suggest to bump the lower bound for `base`, in order to avoid build plans being selected with 7.8 and singletons 2.x.
> Bump lower bound for base, to avoid trying to build 2.x with 7.8.x.

- README.md
- src/Data/Promotion/Prelude/Enum.hs
- src/Data/Singletons/Names.hs
- tests/ByHand2.hs
#148 removed uses of `KProxy` from the codebase, but it's still lurking in a couple of places:
* The `ByHand2` test
* An outdated comment about orphan instances in `Data.Promotion.Prelude.Enum`. Since it's outdated, I opted to remove the whole comment (and the unnecessary `-fno-warn-orphans` flag).
* The `README`. But see my inline comment.
> Remove lingering references to KProxy

- src/Data/Singletons/Single.hs
- tests/compile-and-dump/Singletons/ShowDeriving.ghc82.template
- tests/compile-and-dump/Singletons/ShowDeriving.hs
Previously, we were calling `mkShowInstance` without a surrounding `withLocalDeclarations` to bring in locally declared fixity declarations, which led to incorrect fixity reification. I've fixed this by making `withLocalDeclarations` have a wider berth.
> Fix #192 by increasing the scope of withLocalDeclarations

- CHANGES.md
- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Deriving/Bounded.hs
- src/Data/Singletons/Deriving/Enum.hs
- src/Data/Singletons/Deriving/Infer.hs
- src/Data/Singletons/Deriving/Ord.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/Single/Eq.hs
- src/Data/Singletons/Syntax.hs
- src/Data/Singletons/Util.hs
- tests/SingletonsTestSuite.hs
- tests/SingletonsTestSuiteUtils.hs
- tests/compile-and-dump/GradingClient/Database.ghc82.template
- tests/compile-and-dump/Promote/Newtypes.ghc82.template
- tests/compile-and-dump/Singletons/Maybe.ghc82.template
- tests/compile-and-dump/Singletons/Nat.ghc82.template
- tests/compile-and-dump/Singletons/OrdDeriving.ghc82.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.ghc82.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.hs
- tests/compile-and-dump/Singletons/Star.ghc82.template
- tests/compile-and-dump/Singletons/T178.ghc82.template
- tests/compile-and-dump/Singletons/T187.ghc82.template
This adds the ability to promote and single standalone `deriving` declarations. This provides a usable workaround for #192.
> Add support for standalone deriving declarations

- src/Data/Singletons/Promote.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T197.ghc82.template
- tests/compile-and-dump/Singletons/T197.hs
We needn't promote fixity declarations for identifiers that begin with `$`, since their promoted names are the same as their value-level names. This addresses the first part of #197.
> Add special casing for $ when promoting fixity declarations

- CHANGES.md
- README.md
- src/Data/Promotion/Prelude.hs
- src/Data/Promotion/Prelude/List.hs
- src/Data/Promotion/TH.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Prelude.hs
- src/Data/Singletons/Prelude/List.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/TH.hs
- src/Data/Singletons/TypeLits.hs
- src/Data/Singletons/TypeLits/Internal.hs
- tests/compile-and-dump/GradingClient/Database.ghc82.template
- tests/compile-and-dump/Singletons/T167.ghc82.template
- tests/compile-and-dump/Singletons/Undef.ghc82.template
This lets us remove some special-casing, which is always nice. Note that we can't remote _all_ special casing (see `isException`, for instance), but it's a fair deal better than before.
Fixes #202.
> Make the treatment of undefined less magical

- CHANGES.md
- src/Data/Promotion/Prelude.hs
- src/Data/Promotion/Prelude/List.hs
- src/Data/Singletons/Prelude.hs
- src/Data/Singletons/Prelude/List.hs
- src/Data/Singletons/Prelude/Show.hs
- src/Data/Singletons/TypeLits.hs
- src/Data/Singletons/TypeLits/Internal.hs
I broke the import cycle between `Data.Singletons.Prelude.List` and `Data.Singletons.Prelude.Show` by migrating `:<>` to `Data.Singletons.Prelude.TypeLits`, which is probably a better home for it anyways.
Note that I had to use an alternative implementation of `unwords`, since the one from the `Prelude` doesn't singletonize due to #219.
Fixes #212.
> Add unwords and unlines

- CHANGES.md
- README.md
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Prelude/Instances.hs
- src/Data/Singletons/Promote/Eq.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/Single/Eq.hs
- src/Data/Singletons/Util.hs
- tests/SingletonsTestSuiteUtils.hs
- tests/compile-and-dump/GradingClient/Database.ghc82.template
- tests/compile-and-dump/Singletons/Empty.ghc82.template
- tests/compile-and-dump/Singletons/EqInstances.ghc82.template
- tests/compile-and-dump/Singletons/Maybe.ghc82.template
- tests/compile-and-dump/Singletons/Nat.ghc82.template
- tests/compile-and-dump/Singletons/OrdDeriving.ghc82.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.ghc82.template
- tests/compile-and-dump/Singletons/Star.ghc82.template
- tests/compile-and-dump/Singletons/T178.ghc82.template
- tests/compile-and-dump/Singletons/T187.ghc82.template
This is an overhaul of the way `singletons` handles empty data types (e.g., `data Void`). There are four main changes:
* Before, derived `PEq` instances for empty data types would always return `False`. I've changed this to return `True` instead, for consistency with derived `POrd` instances.
* Before, derived `SEq` instances for empty data types would always error. I've changed this to return `STrue` instead for consistency with derived `PEq` instances.
* Before, derived `SDecide` instances for empty data types would always error. I've changed this to return `Proved ⊥` instead, for (you guessed it) consistency.
* Before, generated `SingKind` instances for empty data types would always error when `fromSing` or `toSing` were invoked. I've changed this so that `fromSing x = case x of {}` …
> Rework handling of empty data types w.r.t. SingKind, PEq, SEq, and SDecide

- CHANGES.md
- singletons.cabal
- src/Data/Promotion/TH.hs
- src/Data/Singletons.hs
- src/Data/Singletons/Decide.hs
- src/Data/Singletons/Internal.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Prelude/Bool.hs
- src/Data/Singletons/Prelude/List.hs
- src/Data/Singletons/Prelude/Num.hs
- src/Data/Singletons/Prelude/Show.hs
- src/Data/Singletons/Single/Monad.hs
- src/Data/Singletons/TypeLits/Internal.hs
- src/Data/Singletons/TypeRepStar.hs
- tests/compile-and-dump/Promote/GenDefunSymbols.ghc82.template
- tests/compile-and-dump/Promote/Prelude.ghc82.template
To accomplish this, I created a new `Data.Singletons.Internal` module to avoid the import cycle that would otherwise ensue when you combine `SomeSing` with `SEq`, `SOrd`, etc.
Fixes #215.
> Add Eq, Ord, Num, Enum, and Bounded instances for SomeSing

- src/Data/Singletons/Promote.hs
- tests/compile-and-dump/GradingClient/Database.ghc82.template
- tests/compile-and-dump/Singletons/Classes.ghc82.template
- tests/compile-and-dump/Singletons/Classes2.ghc82.template
- tests/compile-and-dump/Singletons/DataValues.ghc82.template
- tests/compile-and-dump/Singletons/EnumDeriving.ghc82.template
- tests/compile-and-dump/Singletons/FunDeps.ghc82.template
- tests/compile-and-dump/Singletons/Maybe.ghc82.template
- tests/compile-and-dump/Singletons/Nat.ghc82.template
- tests/compile-and-dump/Singletons/OrdDeriving.ghc82.template
- tests/compile-and-dump/Singletons/PatternMatching.ghc82.template
- tests/compile-and-dump/Singletons/ShowDeriving.ghc82.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.ghc82.template
- tests/compile-and-dump/Singletons/Star.ghc82.template
- tests/compile-and-dump/Singletons/T136.ghc82.template
- tests/compile-and-dump/Singletons/T136b.ghc82.template
- tests/compile-and-dump/Singletons/T167.ghc82.template
- tests/compile-and-dump/Singletons/T178.ghc82.template
- tests/compile-and-dump/Singletons/T187.ghc82.template
- tests/compile-and-dump/Singletons/T190.ghc82.template
Now that [GHC Trac #9063](https://ghc.haskell.org/trac/ghc/ticket/9063) is fixed, we no longer need to put explicit kinds on the type variables in a promoted class instances' associated type family instances. Removing this hack simplifies the code slightly.
However, I opted not to remove the code that calculated the substitution needed for this hack entirely, since it does in fact serve a useful purpose outside of working around Trac #9063: it produces better kind signatures for helper type families used on the RHSes of these associated family instances. I added a Note explaining this.
Fixes #211.
> Fix #211, and document some subtleties of promoteMethod

- src/Data/Singletons/Single.hs
Many mysteries surround the inner machinations of GHC's brain, but as of 8.2, one thing is sure: it will no longer explode. It might panic or become exhausted<sup>of simplifier ticks</sup>, but explosions ain't no thing.
As such, the `checkIfBrainWillExplode` check doesn't serve much of a useful purpose anymore. Let's axe it.
Fixes #210.
> GHC's brain is now explosion-proof

- CHANGES.md
- README.md
- src/Data/Singletons/TypeRepStar.hs
This leverages the power of the new type-indexed `TypeRep` in GHC 8.2 to make the `SingKind Type` kind-safe. Fixes #236.
> Rework Data.Singletons.TypeRepStar to use type-indexed Typeable

- CHANGES.md
- src/Data/Singletons/Prelude/Show.hs
- src/Data/Singletons/TypeLits.hs
This fixes #195 
I moved `div`, `mod`, `divMod` definitions from `Data.Singletons.Prelude.Show` to `Data.Singletons.TypeLits`.
Also, I added division by zero errors.
> Add Div, Mod, DivMod to Data.Singletons.TypeLits. Fix #195

- CHANGES.md
- README.md
- singletons.cabal
- src/Data/Singletons.hs
- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Prelude/Show.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/ShowSing.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Syntax.hs
- src/Data/Singletons/TypeLits.hs
- src/Data/Singletons/TypeLits/Internal.hs
- src/Data/Singletons/TypeRepStar.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/GradingClient/Database.ghc82.template
- tests/compile-and-dump/Singletons/BadShowDeriving.ghc82.template
- tests/compile-and-dump/Singletons/BadShowDeriving.hs
- tests/compile-and-dump/Singletons/DataValues.ghc82.template
- tests/compile-and-dump/Singletons/EmptyShowDeriving.ghc82.template
- tests/compile-and-dump/Singletons/EmptyShowDeriving.hs
- tests/compile-and-dump/Singletons/Maybe.ghc82.template
- tests/compile-and-dump/Singletons/Nat.ghc82.template
- tests/compile-and-dump/Singletons/PatternMatching.ghc82.template
- tests/compile-and-dump/Singletons/ShowDeriving.ghc82.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.ghc82.template
- tests/compile-and-dump/Singletons/T178.ghc82.template
- tests/compile-and-dump/Singletons/T190.ghc82.template
This implements the ideas laid out in #208. Some highlights:
* There is now a `Data.Singletons.ShowSing` module that exports the `ShowSing` class.
* The Template Haskell machinery has been updated so that calling `$(singletons [d| ... |])` on a datatype with a derived `Show` instance will also generate `ShowSing` and `Show` instances for the singleton type. (See `Note [DerivedDecl]`.)
* Along the way, I found it convenient to make deriving `Show` instances for empty datatypes work (instead of simply erroring as before), so I opted to do this.
> Fix #208 by adding a ShowSing class

- src/Data/Singletons/Single/Data.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/GradingClient/Database.ghc82.template
- tests/compile-and-dump/InsertionSort/InsertionSortImp.ghc82.template
- tests/compile-and-dump/Singletons/AsPattern.ghc82.template
- tests/compile-and-dump/Singletons/BoundedDeriving.ghc82.template
- tests/compile-and-dump/Singletons/BoxUnBox.ghc82.template
- tests/compile-and-dump/Singletons/Classes.ghc82.template
- tests/compile-and-dump/Singletons/Classes2.ghc82.template
- tests/compile-and-dump/Singletons/DataValues.ghc82.template
- tests/compile-and-dump/Singletons/HigherOrder.ghc82.template
- tests/compile-and-dump/Singletons/Lambdas.ghc82.template
- tests/compile-and-dump/Singletons/Maybe.ghc82.template
- tests/compile-and-dump/Singletons/Nat.ghc82.template
- tests/compile-and-dump/Singletons/Operators.ghc82.template
- tests/compile-and-dump/Singletons/OrdDeriving.ghc82.template
- tests/compile-and-dump/Singletons/PatternMatching.ghc82.template
- tests/compile-and-dump/Singletons/Records.ghc82.template
- tests/compile-and-dump/Singletons/ShowDeriving.ghc82.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.ghc82.template
- tests/compile-and-dump/Singletons/Star.ghc82.template
- tests/compile-and-dump/Singletons/T159.ghc82.template
- tests/compile-and-dump/Singletons/T163.ghc82.template
- tests/compile-and-dump/Singletons/T197b.ghc82.template
- tests/compile-and-dump/Singletons/T200.ghc82.template
- tests/compile-and-dump/Singletons/T249.ghc82.template
- tests/compile-and-dump/Singletons/T249.hs
- tests/compile-and-dump/Singletons/TopLevelPatterns.ghc82.template
Previously, we were generating implementations of `toSing` like this:
```haskell
$(singletons [d| data Foo a = MkFoo a |])
===>
instance SingKind a => SingKind (Foo a) where
...
toSing (MkFoo b)
= case toSing b :: SomeSing a of
SomeSing c -> SomeSing (SMkFoo c)
```
This works, provided that the types of the fields of `MkFoo` use the same type variables as in the data type itself. But this assumption does not hold true with GADTs, e.g.,
```haskell
$(singletons [d| data Foo a where MkFoo :: x -> Foo x |])
===>
instance SingKind a => SingKind (Foo a) where
...
toSing (MkFoo b)
= case toSing b :: SomeSing x of
SomeSing c -> SomeSing (SMkFoo c)
```
This code will not typecheck, since we claim that `toSing b` has type `SomeSing x`, where `x` is a free variable. But this `x` has a legitimate …
> Fix #249 by sprinkling more pattern signatures

- CHANGES.md
- singletons.cabal
- src/Data/Singletons/ShowSing.hs
- src/Data/Singletons/Sigma.hs
This fixes #256 by adding a `Data.Singletons.Sigma` module that defines `Sigma`, along with some definitions from Agda that were easy to port over to a `singletons` setting.
> Add Data.Singletons.Sigma

- CHANGES.md
- src/Data/Singletons.hs
- src/Data/Singletons/Internal.hs
In https://github.com/goldfirere/singletons/issues/257#issuecomment-335919128, I lamented the lack of defunctionalization symbols for `(~>)`, so this PR adds them, as well as symbols for the other type synonyms in `Data.Singletons`.
Along the way, I realized that we were duplicating the export list for `Data.Singletons` in `Data.Singletons.Internal`, which seems silly, so I axed the explicit export list in `Data.Singletons.Internal`. (No one will notice, after all, since it's internal.)
Fixes #257.
> Promote the type synonyms in Data.Singletons

- src/Data/Singletons/Single.hs
- tests/compile-and-dump/Singletons/T167.ghc82.template
- tests/compile-and-dump/Singletons/Undef.ghc82.template
- tests/compile-and-dump/Singletons/Undef.hs
For reasons described in [`Note [Why error is so special]`](https://github.com/goldfirere/singletons/blob/4e31cde5dfd56584599876b58133221963f5c519/src/Data/Singletons/Single.hs#L527), we shouldn't single applications of `error` or `undefined` to use `applySing`. But in implementing this special case, we totally discarded the arguments of `error`/`undefined`, leading to #263. Fixing this is simple: just apply `error`/`undefined` to their arguments using normal function application.
> Fix #263 by eta expanding exception expressions (like undefined/error)

- src/Data/Singletons/CustomStar.hs
- tests/compile-and-dump/Singletons/Nat.ghc82.template
- tests/compile-and-dump/Singletons/Nat.hs
- tests/compile-and-dump/Singletons/Star.ghc82.template
* Export all of `Data.Singletons.TH` from `Data.Singletons.CustomTypeStar`, since the code that `singletonStar` generates needs it
* Bring some uniformity to the instances that `Rep` derives and the instances that it promotes
* Apply various documentation fixes to `Data.Singletons.CustomTypeStar`
> Fix #264; or, Data.Singletons.CustomTypeStar fixes

- CHANGES.md
- singletons.cabal
- src/Data/Promotion/Prelude/IsString.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Prelude/IsString.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/TypeLits.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/OverloadedStrings.ghc82.template
- tests/compile-and-dump/Singletons/OverloadedStrings.hs
This has been requested enough times (see #247, #248, and #267) that I decided to just implement it.
Now, when the `-XOverloadedStrings` extension is enabled, occurrences of string literals will be promoted/singled using `fromSing` (e.g., you'd promote `"foo"` to `FromSing "foo"` and single `"foo"` to `sFromSing (sing :: Sing "foo")`).
Fixes #247.
> Support OverloadedStrings in singletons

- src/Data/Singletons/Decide.hs
- src/Data/Singletons/TypeRepStar.hs
Currently, the `TestCoercion Sing` instance only works if `Sing` is of kind `Type -> Type`. But this can quite easily work over `Sing`s of any kind... why not do so?
> Generalize the TestCoercion instance for Sing

- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Deriving/Bounded.hs
- src/Data/Singletons/Deriving/Infer.hs
- src/Data/Singletons/Deriving/Ord.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Eq.hs
- src/Data/Singletons/Util.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/GradingClient/Database.ghc82.template
- tests/compile-and-dump/Singletons/EqInstances.ghc82.template
- tests/compile-and-dump/Singletons/Nat.ghc82.template
- tests/compile-and-dump/Singletons/OrdDeriving.ghc82.template
- tests/compile-and-dump/Singletons/Star.ghc82.template
- tests/compile-and-dump/Singletons/T271.ghc82.template
- tests/compile-and-dump/Singletons/T271.hs
`deriving Eq` wasn't using `inferConstraints`, which led to all sorts of shenanigans in #271. This is easily remedied.
Another problem documented in #271 was the fact that `inferConstraints` was fragile in the presence of GADTs, since each constructors' universally quantified type variables could be different from the data type constructor's type variables. To fix this, we apply a substitution on the inferred field types (see `Data.Singletons.Deriving.Infer`).
> Fix #271 by inferring instance contexts more intelligently

- CHANGES.md
- src/Data/Singletons.hs
- src/Data/Singletons/Internal.hs
- tests/compile-and-dump/Singletons/HigherOrder.hs
I've been wanting to make this simplification for a while. Sadly, we're not yet powerful enough to remove the `singFun` family.
Do you see any downsides?
> Remove the TyConN family in favor of TyCon

- src/Data/Singletons/TypeLits.hs
- src/Data/Singletons/TypeLits/Internal.hs
This PR adds the singleton analogue (`%<=`) and defunctionalization symbols to fully cover the *GHC.TypeNats* API, partially just for the sake of completeness.
On a more practical note, though, a bunch of libraries built on native GHC.TypeLits/GHC.TypeNats still build their API's around `<=?`, instead of `CmpNat`, so they're incompatible with *singleton*'s `POrd`/`SOrd` typeclasses.  Having `%<=?` makes these libraries significantly easier to use.
> singleton analogue and defunctionalization symbols for <=?

- CHANGES.md
- singletons.cabal
- src/Data/Promotion/Prelude.hs
- src/Data/Promotion/Prelude/Monoid.hs
- src/Data/Promotion/Prelude/Semigroup.hs
- src/Data/Promotion/Prelude/Show.hs
- src/Data/Singletons/Prelude.hs
- src/Data/Singletons/Prelude/List.hs
- src/Data/Singletons/Prelude/Monoid.hs
- src/Data/Singletons/Prelude/Semigroup.hs
- src/Data/Singletons/Prelude/Show.hs
- src/Data/Singletons/TypeLits.hs
- src/Data/Singletons/TypeLits/Internal.hs
Addresses one part of #184 (specifically, https://github.com/goldfirere/singletons/issues/184#issuecomment-355857980) by introducing promoted/singled versions of `Semigroup` and `Monoid`, as well as exporting them from the `Prelude` to match `base-4.11`. This also adds a `Semigroup`/`Monoid` instance for `Symbol` using `AppendSymbol`.
Unresolved question: do we want to single all of the newtype modifiers from `Data.Monoid` and `Data.Semigroup`? They're perhaps of dubious value (although one possible use case would be to add an indirect `Monoid` instance for `Nat` using [`Sum`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Monoid.html#t:Sum) and [`Product`](https://hackage.haskell.org/package/base-4.10.1.0/docs/Data-Monoid.html#t:Product)).
> Add promoted/singled versions of Semigroup/Monoid

- CHANGES.md
- singletons.cabal
- src/Data/Promotion/Prelude.hs
- src/Data/Promotion/Prelude/Monoid.hs
- src/Data/Promotion/Prelude/Ord.hs
- src/Data/Promotion/Prelude/Semigroup.hs
- src/Data/Singletons/Prelude.hs
- src/Data/Singletons/Prelude/List.hs
- src/Data/Singletons/Prelude/Monoid.hs
- src/Data/Singletons/Prelude/Num.hs
- src/Data/Singletons/Prelude/Ord.hs
- src/Data/Singletons/Prelude/Semigroup.hs
- src/Data/Singletons/Prelude/Semigroup/Internal.hs
- src/Data/Singletons/Prelude/Show.hs
- src/Data/Singletons/TypeLits/Internal.hs
- src/Data/Singletons/Util.hs
Addresses https://github.com/goldfirere/singletons/pull/291#issuecomment-360885936.
This patch looks larger than it actually is due to the need to reorganize the module hierarchy a bit to avoid import cycles.
> Add newtype modifiers to Data.Ord, Data.Semigroup, and Data.Monoid

- .travis.yml
- Setup.hs
- singletons.cabal
- tests/README.md
- tests/SingletonsTestSuite.hs
- tests/SingletonsTestSuiteUtils.hs
In #290, I revamped the test suite to be compatible with `cabal new-build`. Well, to be more accurate, I forced everyone to use `cabal new-build`, and with an extremely recent version of `cabal-install` to boot. This "solution" left a sour taste in my mouth, so I sought a more principled approach, which I believe I've found.
We now use a custom `Setup.hs` script to detect all of the relevant information we'll need to invoke GHC, such as:
* GHC's path
* The database flags to pass it
* The directory in which `singletons.cabal` is located (previously, we had to pass this manually to the test suite, in one of the more disgusting hacks I've ever put into production)
All of this information is put into an autogenerated module `Build_singletons` that the test suite uses in turn. This approach …
> Use Cabal API for more robust tests

- CHANGES.md
- README.md
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Syntax.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T183.ghc84.template
- tests/compile-and-dump/Singletons/T183.hs
By promoting `DPat`s to a `ADPat`, a variant with extra type information, and changing `singPat` to generate extra information to use for creating an extra case expression, we can fix #183 with surprising ease.
> Permit singling of expression and pattern signatures

- CHANGES.md
- README.md
- singletons.cabal
- src/Data/Singletons/TypeError.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T160.ghc84.template
- tests/compile-and-dump/Singletons/T160.hs
This introduces `Data.Singletons.TypeError`, which provides a drop-in replacement for the `TypeError` API from `GHC.TypeLits`. This is based off the design in https://github.com/goldfirere/singletons/issues/160#issuecomment-338246486.
> Fix #160 by introducing Data.Singletons.TypeError

- CHANGES.md
- src/Data/Promotion/Prelude.hs
- src/Data/Singletons/Prelude.hs
- src/Data/Singletons/TypeError.hs
- src/Data/Singletons/TypeLits.hs
- src/Data/Singletons/TypeLits/Internal.hs
- tests/compile-and-dump/Singletons/T160.ghc84.template
In GHC 8.0, `base` added `HasCallStack` constraints to `error` and `undefined`, but these never found their ways into their singled counterparts in `singletons`. Let's do so.
GHC 8.0 also added an `errorWithoutStackTrace` function to the `Prelude` which does _not_ have a `HasCallStack` constraint, so for the sake of completeness, I added this too.
> Add HasCallStack constraints to error-throwing functions

- CHANGES.md
- README.md
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Promote/Defun.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Syntax.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T178.ghc84.template
- tests/compile-and-dump/Singletons/T313.ghc84.template
- tests/compile-and-dump/Singletons/T313.hs
This patch is really quite simple in the end—it just augments `PartitionedDecs` with extra fields for type synonym and family declarations, and plumbs them through to `defunctionalize`.
Fixes #313, and fixes #198 (insofar as it does all that singletons can, short of fixing #12564 itself).
> Produce defunctionalization symbols for type synonym/family declarations

- CHANGES.md
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Promote/Defun.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Fixity.hs
- src/Data/Singletons/Syntax.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/Classes.ghc84.template
- tests/compile-and-dump/Singletons/Fixity.ghc84.template
- tests/compile-and-dump/Singletons/ShowDeriving.ghc84.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.ghc84.template
- tests/compile-and-dump/Singletons/T159.ghc84.template
- tests/compile-and-dump/Singletons/T197.ghc84.template
- tests/compile-and-dump/Singletons/T197b.ghc84.template
- tests/compile-and-dump/Singletons/T322.ghc84.template
- tests/compile-and-dump/Singletons/T323.hs
This mostly involves some minor plumbing to `defunctionalize` and its call sites. Along the way, I did a little refactoring of `lde_infix`, converting it from an association list to a proper `Map` to facilitate faster lookups (since we now need to do so before calling `defunctionalize`, which takes a `Fixity` argument, in certain spots).
> Fix #323 by generating fixity declarations for defunctionalization symbols

- singletons.cabal
- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Deriving/Bounded.hs
- src/Data/Singletons/Deriving/Enum.hs
- src/Data/Singletons/Deriving/Infer.hs
- src/Data/Singletons/Deriving/Ord.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Deriving/Util.hs
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/Syntax.hs
- src/Data/Singletons/Util.hs
While working on https://github.com/goldfirere/singletons/issues/184 (in particular, while trying to add the ability to derive `Functor`, `Foldable`, and `Traversable`), I discovered that the code around `Data.Singletons.Deriving.*` is a bit icky. This PR is an attempt to clean it up a little in preparation for https://github.com/goldfirere/singletons/issues/184. In particular:
* I introduce a new internal module, `Data.Singletons.Deriving.Util`, which for now only contains two things. (I'll need to add more things later.)
* Within `Data.Singletons.Deriving.Util`, I introduce a `DerivDesc` type synonym, which gives a generic type signature for deriving an instance. It turns out that this type was used in several places across `singletons`, so I found it convenient to have a common name …
> Refactor deriving-related code

- CHANGES.md
- README.md
- singletons.cabal
- src/Data/Promotion/Prelude.hs
- src/Data/Promotion/Prelude/Applicative.hs
- src/Data/Promotion/Prelude/Functor.hs
- src/Data/Promotion/Prelude/Monad.hs
- src/Data/Promotion/Prelude/Monad/Zip.hs
- src/Data/Singletons/Prelude.hs
- src/Data/Singletons/Prelude/Applicative.hs
- src/Data/Singletons/Prelude/Functor.hs
- src/Data/Singletons/Prelude/List/NonEmpty.hs
- src/Data/Singletons/Prelude/Monad.hs
- src/Data/Singletons/Prelude/Monad/Internal.hs
- src/Data/Singletons/Prelude/Monad/Zip.hs
- src/Data/Singletons/Prelude/Monoid.hs
- src/Data/Singletons/Prelude/Semigroup.hs
- src/Data/Singletons/Prelude/Semigroup/Internal.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T184.ghc84.template
- tests/compile-and-dump/Singletons/T184.hs
At long last, this adds supports for `Monad` and friends. This means we can properly promote and single:
* `do`-notation
* List comprehensions
* `ParallelListComp` (through the `Data.Singletons.Prelude.Monad.Zip` module)
Nothing needed to be changed from the code generation side to make this work—all that was needed was some minor tweaks to the original source code:
* Some extra kind signatures had to be inserted to avoid CUSK issues (e.g., `class Functor (f :: Type -> Type)`).
* Some definitions which rely on infinite lists, such as `some`, `many`, and `forever`, cannot be promoted.
One thing this patch does _not_ do (since it's already pretty large) is add support for `Foldable` and `Traversable`. As a result, I've left some exports from `Data.Singletons.Prelude.Monad` commented out, …
> Fix #184 by adding support for monads 

- src/Data/Singletons/Single.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T332.ghc84.template
- tests/compile-and-dump/Singletons/T332.hs
Note that `singTopLevelDecs` itself also invokes `withLocalDeclarations`, so to avoid grabbing the same set of local declarations twice in `singletons`, I split up a call to `wrapDesugar` to invoke `withLocalDeclarations` only over the scope of `dsDecs`.
> Fix #332 by using local declarations when desugaring in `singletons`

- src/Data/Singletons/Prelude/Eq.hs
- src/Data/Singletons/TypeLits/Internal.hs
- src/Data/Singletons/TypeRepTYPE.hs
> Replace the default implementation of PEq((==)) with a custom type family

- src/Data/Singletons/Internal.hs
This silences `-Wincomplete-patterns`.
> Make Sing and FromSing complete patterns

- CHANGES.md
- README.md
- src/Data/Singletons.hs
- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Prelude/Monoid.hs
- src/Data/Singletons/Prelude/Semigroup.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/ShowSing.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Syntax.hs
- src/Data/Singletons/TypeLits.hs
- src/Data/Singletons/TypeRepTYPE.hs
- tests/SingletonsTestSuiteUtils.hs
- tests/compile-and-dump/GradingClient/Database.ghc86.template
- tests/compile-and-dump/Singletons/DataValues.ghc86.template
- tests/compile-and-dump/Singletons/EmptyShowDeriving.ghc86.template
- tests/compile-and-dump/Singletons/Maybe.ghc86.template
- tests/compile-and-dump/Singletons/Nat.ghc86.template
- tests/compile-and-dump/Singletons/PatternMatching.ghc86.template
- tests/compile-and-dump/Singletons/ShowDeriving.ghc86.template
- tests/compile-and-dump/Singletons/StandaloneDeriving.ghc86.template
- tests/compile-and-dump/Singletons/T178.ghc86.template
- tests/compile-and-dump/Singletons/T190.ghc86.template
This implements a nice simplification permitted by the existence of `QuantifiedConstraints`. We can take the `ShowSing` class, which is wildly ad hoc, and convert it into a much more svelte quantified constraint synonym. In particular, we can take code like this:
```haskell
instance (ShowSing a, ShowSing b) => ShowSing (Either a b) where showsSingPrec = ...
instance (ShowSing a, ShowSing b) => Show (Sing (e :: Either a b)) where showsPrec = showsSingPrec
```
And replace it with a much more concise equivalent:
```haskell
type ShowSing k = (forall (z :: k). Show (Sing z) :: Constraint)
deriving instance (ShowSing a, ShowSing b) => Show (Sing (e :: Either a b))
```
This means that anyone who singles derived `Show` instances will now need to enable `QuantifiedConstraints` and …
> Use QuantifiedConstraints to make ShowSing less ad hoc

- src/Data/Singletons/Promote/Type.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Promote/T361.ghc86.template
- tests/compile-and-dump/Promote/T361.hs
- tests/compile-and-dump/Singletons/LambdaCase.ghc86.template
This removes a vesitigal special case for promoting `String`s, as well as an unnecessary restriction on promoting type literals, from `promoteType`.
> Fix #361 by removing ad hockery from promoteType

- CHANGES.md
- README.md
- src/Data/Singletons/Deriving/Bounded.hs
- src/Data/Singletons/Deriving/Enum.hs
- src/Data/Singletons/Deriving/Foldable.hs
- src/Data/Singletons/Deriving/Functor.hs
- src/Data/Singletons/Deriving/Ord.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Deriving/Traversable.hs
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Syntax.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T358.ghc86.template
- tests/compile-and-dump/Singletons/T358.hs
This turns out to be not so bad implementation-wise. The key step is stashing an extra `Map Name DType` in each `InstDecl` to store each instance signature, and consulting that when trying to determine what a instance method's type should be (before all the other tricks we currently pull).
Fixes #358 (at least, to the extent that is currently possible with today's GHC).
> Support promoting and singling InstanceSigs

- CHANGES.md
- src/Data/Singletons/Sigma.hs
Having to create defunctionalization symbols for `Σ` is annoying since morally, `Σ` ought to be defined as a simple partial application of `Sigma`, like so:
```haskell
type Σ = Sigma
```
Until recently, I thought doing so was impossible due to GHC restrictions (see [Trac #13408](https://ghc.haskell.org/trac/ghc/ticket/13408)). But as it turns out, I was mistaken. There is actually an extremely straightforward way to make the above definition kind-check: just enable `ImpredicativeTypes`!
This patch implements that suggestion, and since the defunctionalization symbols for `Σ` are no longer necessary, I have removed them. In the event that someone ever fixes Trac #13408, we can remove the use of `ImpredicativeTypes`, so I have added a Note reminding us to do so should the time ever come.
> Define Σ as a partial application of Sigma

- .travis.yml
- singletons.cabal
- tests/SingletonsTestSuite.hs
This is a better attempt to fix #123 in which I use `tasty-1.2`'s new API for expressing test dependencies. (I previously attempted to parallelize the test suite in commit 7962d08821e8d5b82b5d754488ee3a41cca4b10d, but that ended disastrously. See https://github.com/goldfirere/singletons/issues/123#issuecomment-363908783 for more details.)
I also use `-maxN16` this time instead of `-N`. It's unclear how well this scales, so I decided to be cautious at cap it off at 16. Testing this locally on my machine, using `-maxN16` reduces the build time from about 90 to 15 seconds, which is pretty nice in its own right. (If more adventurous users want to attempt using more threads, they can always override this themselves.)
> Parallelize the test suite (for real this time)

- CHANGES.md
- cabal.project
- singletons.cabal
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Prelude.hs
- src/Data/Singletons/Prelude/Monad.hs
- src/Data/Singletons/Prelude/Monad/Fail.hs
- src/Data/Singletons/Prelude/Monad/Internal.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Promote/Monad.hs
- src/Data/Singletons/Promote/Type.hs
- src/Data/Singletons/Single/Monad.hs
- src/Data/Singletons/Util.hs
`base-4.13` removes the `fail` method from the `Monad` class, leaving it exclusively as a method of `MonadFail`, which is now re-exported from the `Prelude`. This patch mirrors these changes on the `singletons` side:
* `Fail`/`sFail` has been ripped out of `{P,S}Monad` in favor of new `{P,S}MonadFail` classes.
* A couple of functions in `singletons` needed to have their `Monad` constraints strengthened to `MonadFail` to mirror similar changes in `th-desugar`.
Addresses one bullet point of #356.
> Adapt to MonadFail-related changes in base-4.13

- src/Data/Singletons/Util.hs
This fixes an issue I am getting on GHCJS:
```
src/Data/Singletons/Util.hs:69:16: error:
• Couldn't match type ‘Integer’ with ‘Int’
Expected type: q Int
Actual type: q Uniq
• In the expression: return n
In a case alternative: NameU n -> return n
In a stmt of a 'do' block:
case flav of
NameU n -> return n
_ -> error "Internal error: `qNewName` didn't return a NameU"
|
69 |     NameU n -> return n
|                ^^^^^^^^
```
> Use fromIntegral to avoid GHCJS conflict

- CHANGES.md
- src/Data/Singletons/Internal.hs
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Promote/Monad.hs
- src/Data/Singletons/Promote/Type.hs
- src/Data/Singletons/Single/Monad.hs
- src/Data/Singletons/Util.hs
This fixes #356 for good by checking off the last two tasks in its description:
* Now that `MonadFail` is exported by the `Prelude`, we no longer need to import `Control.Monad.Fail`.
* We can use visible kind applications to simplify the presentation of `ApplyTyCon` to make it obvious how the two equations differ.
> Fix the remainder of #356

- CHANGES.md
- src/Data/Singletons.hs
It turns out that we don't need the `Enum` instance for `SomeSing` to have a `SingKind` constraint, as we can get away without needing the use of `fromSing` in the implementations of `enumFromTo` and `enumFromThenTo` if we convert an `SList @a` directly into a list of `SomeSing a`s without recursively invoking `fromSing`. As an added bonus, this will likely make the code more efficient at runtime as well.
> Make SomeSing's Enum efficient more efficient and general

- Setup.hs
As observed in commercialhaskell/stackage#4646, newer versions of `stack` use `.ghc.environment` files in such a way that they are picked up while invoking the test suite, which causes a `Loaded package environment from ...` message to be printed and breaks the expected test output. To avoid this issue, we simply pass `-package-env=-` when shelling out to `ghc` in the test suite so that it never picks up any ambient `.ghc.environment` files.
> Don't pick up .ghc.environment files when running tests

- CHANGES.md
- src/Data/Singletons/ShowSing.hs
- src/Data/Singletons/Sigma.hs
* `SSigma`, the singleton type for `Sigma`, has been added. This fixes #366.
* A `Show` instance has been added for `Sigma` (and `SSigma`) by using copious amounts of quantified constraints. The behavior of these instances closely resembles the `Show` implementation for `DPair` in Idris' standard library: https://github.com/idris-lang/Idris-dev/blob/dbe521ff74189df85121abe454f86894de7fd75c/libs/prelude/Prelude/Show.idr#L195-L196
* New functions `fstSigma` and `sndSigma` (as well as their type-level counterparts) have been added. To avoid being a duplicate of `fstSigma`, `projSigma1` has been redefined to have a new type signature that uses continuation-passing style, much like its cousin `projSigma2`.
* New functions `currySigma` and `uncurrySigma` have been added. This fixes #359 and …
> Some API additions and reorganization for Data.Singletons.Sigma

- .travis.yml
- CHANGES.md
- cabal.project
- singletons.cabal
- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Deriving/Util.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Promote/Defun.hs
- src/Data/Singletons/Promote/Type.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/Single/Type.hs
- src/Data/Singletons/Util.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T401.ghc88.template
- tests/compile-and-dump/Singletons/T401.hs
`singletons` can't handle higher-rank types. You might think that these sorts of types would naturally be rejected when promoting or singling them, but that actually turns out not to be the case! (See #401 for examples of higher-rank types that squeeze through the cracks.)
Luckily, the additional machinery that `th-desuguar` adds in goldfirere/th-desugar#125 makes it much easier to detect these. Instead of using `unravelDType` to decompose a function type (which permits all sorts of higher-rank gubbins), we use a restricted version called `unravelVanillaDType`, which throws an error if anything higher-rank is detected. See `Note [Vanilla-type validity checking during promotion]` in `D.S.Promote.Type` for a full explanation of what a "vanilla" type is.
Fixes #401.
> Properly reject higher-rank types during promotion/singling

- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Util.hs
`promoteMethod` is unnecessarily complicated. It does a lot of work to construct a type family defintion and defunctionalization symbols for the method's default implementation. However, these definitions were actually computed earlier in the call to `promoteLetDecRHS`, but `promoteMethod` throws them away and recomputes them anyway!
Instead, we can simply reuse the results of `promoteLetDecRHS`, which this patch accomplishes. This also allows the return type of `promoteLetDecRHS` to be simplified slightly, as we no longer need to return a nested tuple of assorted things. Instead, we now have a flat tuple of assorted things :)
This commit is purely an internal refactor—no user-facing changes here.
> Refactor internals of promoteMethod

- CHANGES.md
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/Single/Fixity.hs
- src/Data/Singletons/Util.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T197b.ghc88.template
- tests/compile-and-dump/Singletons/T412.ghc88.template
- tests/compile-and-dump/Singletons/T412.hs
Issue #412 revealed so many bugs in how `singletons` handles fixity declarations that it drove me to write `Note [singletons and fixity declarations]` to document that various wisdom one needs to handle them correctly:
* `singInfixDecl` now returns a `Maybe`, since the only type constructors that need to be singled are classes. `promoteInfixDecl` now also makes a similar special case when dealing with type constructors.
* The `promoteReifiedInfixDecls`/`singReifiedInfixDecls` functions are now used in the code that promotes/singles classes to ensure that their fixity declarations will be handled even if `genSingletons` is used instead of the `singletons` functions.
Fixes #412.
> Handle type constructors' fixity declarations more carefully

- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Promote/Defun.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Syntax.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T414.ghc88.template
- tests/compile-and-dump/Singletons/T414.hs
Associated type families were going through the same code path as top-level open type families during defunctionalization. But top-level open type families always default any type variable binders without explicit kinds to be of kind `Type`. This approach does not always work for associated type families, leading to the bug observed in #414.
This fixes the issue by partitioning associated type families separately from other open type families in `D.S.Partition` and introducing a new `defunAssociatedTypeFamilies` function in `D.S.Promote.Defun` to handle them. I've also added some more comments in various places to make things a bit clearer.
Fixes #414.
> Handle associated types properly in D.S.Promote.Defun

- CHANGES.md
- Makefile
- README.md
- singletons.cabal
- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Deriving/Show.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Partition.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Promote/Defun.hs
- src/Data/Singletons/Promote/Eq.hs
- src/Data/Singletons/Promote/Monad.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/Single/Defun.hs
- src/Data/Singletons/Single/Eq.hs
- src/Data/Singletons/Single/Fixity.hs
- src/Data/Singletons/Single/Monad.hs
- src/Data/Singletons/Single/Type.hs
- src/Data/Singletons/TH.hs
- src/Data/Singletons/TH/Options.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T150.golden
- tests/compile-and-dump/Singletons/T150.hs
- tests/compile-and-dump/Singletons/T204.golden
- tests/compile-and-dump/Singletons/T204.hs
This patch introduces an `Options` data type and an `mtl`-like `OptionsMonad` class for monads that carry `Options`. At present, the only things one can do with `Options` are:
* Toggle the generation of `SingKind` instances. Suppressing `SingKind` instances provides an effective workaround for #150.
* Hook into the TH machinery's naming conventions for promoted and singled names. This fixes #204.
The vast majority of this patch simply adds plumbing by using `OptionsMonad` in places that need it. See the `D.S.TH.Options` module for where most of the new code is housed, as well as the `T150` and `T204` test cases for examples of how to use it.
> Introduce Options and OptionsMonad

- CHANGES.md
- src/Data/Singletons/Prelude/Base.hs
- src/Data/Singletons/Prelude/Function.hs
- src/Data/Singletons/Prelude/Functor.hs
- src/Data/Singletons/Prelude/List/Internal.hs
- src/Data/Singletons/Prelude/Monad.hs
- src/Data/Singletons/Prelude/Monad/Internal.hs
- src/Data/Singletons/Prelude/Num.hs
- src/Data/Singletons/Prelude/Ord.hs
- src/Data/Singletons/Prelude/Semigroup/Internal.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Fixity.hs
- src/Data/Singletons/TH/Options.hs
- src/Data/Singletons/Util.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T326.golden
- tests/compile-and-dump/Singletons/T326.hs
This patch:
* Introduces a `genQuotedDecs :: Bool` option that controls whether the `q [Dec]` arguments in the `promote` and `singletons` functions should be generated as part of their output.
* Refactor `promote{Only}` and `singletons{Only}` to use `genQuotedDecs`.
* Changes `D.S.Promote.promoteInfixDecl` so that it _does_ promote fixity declarations for infix names when `genQuotedDecs` is `False`. (See the updated `Note [singletons and fixity declarations]` in `D.S.Single.Fixity`, wrinkle 1, for a more detailed explanation.) This fixes #326 in a much more robust way than the previous hacky workaround in commit 40c736ffc3b3a4954d5e44f759344690424ab449.
> Add genQuotedDecs option, generate fixity decs for infix names if False

- CHANGES.md
- src/Data/Singletons/Prelude/List.hs
- src/Data/Singletons/Prelude/List/Internal.hs
Per the discussion in https://github.com/goldfirere/singletons/issues/433#issuecomment-582912446, these definitions are subtly bogus. Let's just remove them.
> Remove the promoted versions of GenericTake et al.

- CHANGES.md
- singletons.cabal
- src/Data/Singletons/Prelude/Foldable.hs
- src/Data/Singletons/Prelude/Monad/Zip.hs
- src/Data/Singletons/Prelude/Proxy.hs
- src/Data/Singletons/Prelude/Traversable.hs
Even in a library as deeply entrenched in type-level trickery as
`singletons` is, there are still some situations that call for
proxies. See, for example, the use case in #435, which uses not only
the classic `Proxy` data type, but also the /singled/ version of
`Proxy`! The author of this use case requested that the singled
version of `Proxy` be made available in `singletons`, so this patch
accomplishes that.
Fixes #435.
> Add Data.Singletons.Prelude.Proxy

- CHANGES.md
- README.md
- src/Data/Singletons/CustomStar.hs
- src/Data/Singletons/Prelude/Applicative.hs
- src/Data/Singletons/Prelude/Const.hs
- src/Data/Singletons/Prelude/Foldable.hs
- src/Data/Singletons/Prelude/Identity.hs
- src/Data/Singletons/Prelude/Monoid.hs
- src/Data/Singletons/Prelude/Ord.hs
- src/Data/Singletons/Prelude/Semigroup.hs
- src/Data/Singletons/Prelude/Traversable.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/Util.hs
- tests/compile-and-dump/Promote/Newtypes.golden
- tests/compile-and-dump/Promote/T180.golden
- tests/compile-and-dump/Singletons/Records.golden
- tests/compile-and-dump/Singletons/ShowDeriving.golden
- tests/compile-and-dump/Singletons/T332.golden
- tests/compile-and-dump/Singletons/T412.golden
- tests/compile-and-dump/Singletons/T412.hs
`singletons` has traditionally singled record selectors "in-place".
For example, `data T = MkT { unT :: Bool }` would be singled as
`data ST :: T -> Type where SMkT :: { sUnT :: Sing b } -> ST (MkT b)`.
This may seem like a sensible choice, but it has some unfortunate
consequences:
* This function will not typecheck when singled:
```hs
f :: T -> Bool
f = unT
```
This is because the type of `sUnT` is `Sing (MkT b) -> b`, which
is not general enough for the type of `sF`, which is
`Sing (t :: T) -> Sing (F t :: Bool)`.
* It is impossible to single a data type with multiple constructors
that share a record name, since each occurrence of a record
selector in a data type is required to have the same type.
For these reasons and more discussed in
`Note [singletons and record selectors]` in …
> Single record selectors as top-level functions

- src/Data/Singletons/Single.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/GradingClient/Database.golden
- tests/compile-and-dump/InsertionSort/InsertionSortImp.golden
- tests/compile-and-dump/Singletons/AsPattern.golden
- tests/compile-and-dump/Singletons/CaseExpressions.golden
- tests/compile-and-dump/Singletons/DataValues.golden
- tests/compile-and-dump/Singletons/FunDeps.golden
- tests/compile-and-dump/Singletons/LetStatements.golden
- tests/compile-and-dump/Singletons/PatternMatching.golden
- tests/compile-and-dump/Singletons/T160.golden
- tests/compile-and-dump/Singletons/T183.golden
- tests/compile-and-dump/Singletons/T183.hs
- tests/compile-and-dump/Singletons/T296.golden
- tests/compile-and-dump/Singletons/T296.hs
- tests/compile-and-dump/Singletons/T54.golden
- tests/compile-and-dump/Singletons/TopLevelPatterns.golden
When a local function (1) lacks a type signature, and (2) has no arguments, we single it such that its type signature has a return type of `Sing @_ Blah` instead of `Sing Blah`. This prevents kind generalization from mucking with the kind of `Blah`, which can be undesirable. For the complete story, refer to `Note [Disable kind generalization for local functions if possible]` in `D.S.Single`.
Aside from fixing #296, this allows us to finally uncomment a line of code in `T183` that relies on this fix.
> Disable kind generalization when singling sig-less local functions

- README.md
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/TH/Options.hs
This patch fleshes out some more details about what `singletons`
can and can't do in its `README`. The key changes are:
1. There is a new "Promotion and partial application" section that
explains what defunctionalization is in some amount of detail.
There is also a new subsection that explains the limitations of
the `genDefunSymbols` function that were observed in #429.
2. The "Supported Haskell constructs" section has received some more
love. Some Haskell features were inaccurately characterized
(e.g., pattern signatures are really only partially supported),
so I also reorganized some of the bullet points. I have also added
a new bullet point for `ScopedTypeVariables` under the
"Little to no support" section, as #433 reveals that promoting
functions that rely on the behavior of …
> More thoroughly document what is (and isn't) allowed in the README

- src/Data/Singletons/Internal.hs
- tests/ByHand.hs
GHC's [simplified subsumption proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0287-simplify-subsumption.rst) removes deep skolemization, which `singletons`' TH machinery relied on in order to typecheck the uses of `singFun1` _et al._ that it generates. The reason it relied on deep skolemization is because `SingFunction1` _et al._ were defined with `forall`s nested underneath arrow types. In this patch, we redefine `SingFunction1` _et al._ so that all of the `forall`s are up front, making deep skolemization unnecessary when applying `singFun1` _et al._
...well, unnecessary 99% of the time. It turns out there is one place in `ByHand` that defines a singled function with nested `forall`s that no longer works with the new version of `singFun2`. But `singletons` …
> Adapt to simplified subsumption in GHC

- src/Data/Singletons/Single/Data.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/BoundedDeriving.golden
- tests/compile-and-dump/Singletons/FunctorLikeDeriving.golden
- tests/compile-and-dump/Singletons/T150.golden
- tests/compile-and-dump/Singletons/T271.golden
- tests/compile-and-dump/Singletons/T296.golden
- tests/compile-and-dump/Singletons/T297.golden
- tests/compile-and-dump/Singletons/T371.golden
- tests/compile-and-dump/Singletons/T378a.golden
- tests/compile-and-dump/Singletons/T378b.golden
- tests/compile-and-dump/Singletons/T412.golden
- tests/compile-and-dump/Singletons/T453.golden
- tests/compile-and-dump/Singletons/T453.hs
If a data declaration's SAK were to use an explicit `forall`, then `singletons` would have no issues singling it. If it didn't use an explicit `forall`, however, then it would topple over. The fix: quantify the kind variables in a SAK ourselves when a SAK lacks an explicit `forall`. The `D.S.Single.Type.singTypeKVBs` function does the exact same thing, as it turns out, but I somehow overlooked this before.
While I was in town, I took the liberty of cleaning up a couple of code smells:
* There were a couple of invocations of `promoteType` that were completely unnecessary.
* In the case where a data declaration lacks a SAK, I now explicitly quantify over kind variables as well as type variables. Not quantifying over kind variables in a data declaration's return kind is not an error per se …
> Fix #453 by always explicitly quantifying SAK kind variables

- .travis.yml
- CHANGES.md
- README.md
- cabal.project
- singletons.cabal
- src/Data/Singletons/Deriving/Enum.hs
- src/Data/Singletons/Deriving/Util.hs
- src/Data/Singletons/Promote.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T443.golden
- tests/compile-and-dump/Singletons/T443.hs
This patch updates the `th-desugar` submodule to incorporate
goldfirere/th-desugar#139, which:
1. Removes the horribly buggy `conExistentialTvbs` function, and
2. Simplifies `getRecordSelectors` so that it does not bother trying
to filter out naughty record selectors.
Incorporating (2) amounts to fixing #443, for which the test case was
rejected due to `conExistentialTvbs` being overly conservative with
GADTs. To adapt to (1), certain validity checks in `singletons` which
previously used `conExistentialTvbs` will now be less precise. This
isn't a huge deal—it just means that erroneous programs which
`singletons` used to give specialized error messages for will now
just go through, resulting in an error message on GHC's behalf.
Fixes #443.
> Use simpler version of getRecordSelectors from th-desugar

- src/Data/Singletons/Deriving/Enum.hs
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Prelude/Ord.hs
- src/Data/Singletons/Prelude/Proxy.hs
- src/Data/Singletons/Prelude/Show.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Single.hs
- src/Data/Singletons/TH.hs
- src/Data/Singletons/TH/Options.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/EnumDeriving.golden
- tests/compile-and-dump/Singletons/Maybe.golden
- tests/compile-and-dump/Singletons/Nat.golden
- tests/compile-and-dump/Singletons/NegativeLiterals.golden
- tests/compile-and-dump/Singletons/NegativeLiterals.hs
- tests/compile-and-dump/Singletons/OverloadedStrings.golden
- tests/compile-and-dump/Singletons/T166.golden
- tests/compile-and-dump/Singletons/T178.golden
- tests/compile-and-dump/Singletons/T190.golden
- tests/compile-and-dump/Singletons/T271.golden
- tests/compile-and-dump/Singletons/T358.golden
- tests/compile-and-dump/Singletons/T371.golden
For the reasons spelled out in the new `Note [Wired-in Names]` in
`D.S.Names`, we wish to generate all promoted and singled `Name`s
completely unqualified. This patch accomplishes that by deleting
wired-in `Name`s from `D.S.Names` and replacing them with proper
`promotedValueName`s and `singledValueName`s.
Doing this revealed that certain test cases in the test suite no
longer compiled, as they were generating `Name`s that were no longer
in scope due to the lack of wiring in. This is easily remedied by
re-exporting these names from `D.S.TH`, which we should have been
doing all along.
Fixes #452.
> Don't wire in promoted or singled Names

- CHANGES.md
- README.md
- src/Data/Singletons/Names.hs
- src/Data/Singletons/Promote.hs
- src/Data/Singletons/Promote/Defun.hs
- src/Data/Singletons/Promote/Type.hs
- src/Data/Singletons/Single/Data.hs
- src/Data/Singletons/TH/Options.hs
- tests/SingletonsTestSuite.hs
- tests/compile-and-dump/Singletons/T450.golden
- tests/compile-and-dump/Singletons/T450.hs
This allows teaching the Template Haskell machinery about data types that need to be promoted in special ways (e.g., promoting `Nat` to `Natural`). This makes working with such types much less painful than before, where one always had to resort to writing such code by hand.
Fixes #450.
> Add promotedDataTypeOrConName option for custom promotion

- singletons-base/CHANGES.md
- singletons-base/src/Prelude/Singletons.hs
- singletons-base/tests/compile-and-dump/GradingClient/Database.hs
A recent perusal of `Prelude.Singletons` revealed that there were several functions from the `Prelude` that `Prelude.Singletons` didn't export, and conversely, there were various functions that `Prelude.Singletons` does export that the `Prelude` doesn't! Part of the reason why this went unnoticed for so long is that the structure of `Prelude.Singletons`' exports is rather haphazard, so attempting to eyeball the differences between the export lists of `Prelude.Singletons` and the `Prelude` was unnecessarily difficult.
This cleans things up by restructuring `Prelude.Singletons`' export list to very closely mirror the `Prelude`'s export list. For each exported item in the `Prelude` that `Prelude.Singletons` _doesn't_ export, a comment has been left in the corresponding place in …
> Make Prelude.Singletons mirror the Prelude more closely

- singletons-th/src/Data/Singletons/TH/Util.hs
The `D.S.TH.Util.isFunTy` function is rather suspicious, as it returns `True` for `DForallT`. But more to the point, it is not used anywhere. Let's just delete it.
> Delete dead code from D.S.TH.Util

- .travis.yml
- cabal.project
- singletons-base/tests/compile-and-dump/Singletons/T342.golden
- singletons-base/tests/compile-and-dump/Singletons/T342.hs
- singletons-th/src/Data/Singletons/TH/CustomStar.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Util.hs
- singletons-th/src/Data/Singletons/TH/Names.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Promote/Defun.hs
- singletons-th/src/Data/Singletons/TH/Promote/Type.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Data.hs
- singletons-th/src/Data/Singletons/TH/Single/Defun.hs
- singletons-th/src/Data/Singletons/TH/Single/Type.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
- singletons-th/src/Data/Singletons/TH/Util.hs
This updates the `th-desugar` submodule to commit goldfirere/th-desugar@ca761285741c16c704a4044f551faf4292432d6a, which incorporates several recent developments:
* `DTyVarBndr`s are now parameterized by a `flag` type parameter. This has several ripple effects throughout `singletons`, as various functions now need to care about `Specificity`.
* `decToTH` returns a `Dec` rather than `[Dec]`. This is used in a handful of places in `singletons` and need to be updated accordingly.
* The type of `dsTvb` is different on pre-9.0 versions of GHC, so we replace uses of `dsTvb` with `dsTvbUnit` in `singletons-th` to ensure backwards compatibility. When we drop support for pre-9.0 versions of GHC in `singletons-th`, we can revisit this.
> Update th-desugar submodule to ca76128

- singletons/src/Data/Singletons.hs
This isn't strictly required, but it makes them look slightly cleaner.
Addresses one bullet point of #439.
> Use inferred kind variable in signatures for demote, SingI

- singletons-base/CHANGES.md
- singletons-base/src/Data/Semigroup/Singletons.hs
- singletons-base/src/Data/Semigroup/Singletons/Internal.hs
`Option` has been deprecated in `base-4.15.0.0` (in anticipation of its eventual removal from `base`). To avoid `-Wdeprecations` warnings, let's just remove its use from `singletons-base`.
> Remove use of Data.Semigroup.Option

- singletons-base/src/Data/Monoid/Singletons.hs
- singletons-base/src/Data/Semigroup/Singletons.hs
- singletons-base/src/Data/Semigroup/Singletons/Internal.hs
- singletons-base/src/Text/Show/Singletons.hs
`UndecidableInstances` no longer implies `FlexibleContexts` in instance declarations as of GHC 9.2 (see https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.2#undecidableinstances-no-longer-implies-flexiblecontexts-in-instance-declarations), so we need to enable `FlexibleContexts` in a handful of additional places to make `singletons` compile with GHC 9.2. Luckily, this is a backwards compatible change, so I decided to just make this change now.
(Originally noticed in `head.hackage` in https://gitlab.haskell.org/ghc/head.hackage/-/merge_requests/138.)
> Enable FlexibleContexts in more places to support GHC 9.2

- README.md
- singletons-base/tests/compile-and-dump/Singletons/T443.golden
- singletons-base/tests/compile-and-dump/Singletons/T443.hs
- singletons-base/tests/compile-and-dump/Singletons/T450.golden
- singletons-base/tests/compile-and-dump/Singletons/T450.hs
- singletons-base/tests/compile-and-dump/Singletons/T453.golden
- singletons-base/tests/compile-and-dump/Singletons/T453.hs
- singletons-th/CHANGES.md
- singletons-th/singletons-th.cabal
- singletons-th/src/Data/Singletons/TH/Options.hs
This avoids the need to explicitly `lift` quoted declarations into `OptionsM` in combination with `withOptions`.
Addresses one bullet point of #439.
> Add a Quote instance for OptionsM

- singletons-base/src/Data/Functor/Const/Singletons.hs
- singletons-th/src/Data/Singletons/TH/Single/Type.hs
Wrinkles 2 and 3 are still relevant in this Note, even after the advent of explicit specificity, but only in more limited circumstances. This updates the Note to point out these circumstances.
Addresses one bullet point of #439.
> Update Note [Preserve the order of type variables during singling]

- README.md
- singletons-base/src/Data/Singletons/Base/Instances.hs
- singletons-base/src/Data/Singletons/Base/SomeSing.hs
- singletons-base/tests/compile-and-dump/GradingClient/Database.golden
- singletons-base/tests/compile-and-dump/Singletons/DataValues.golden
- singletons-base/tests/compile-and-dump/Singletons/EmptyShowDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/Maybe.golden
- singletons-base/tests/compile-and-dump/Singletons/Nat.golden
- singletons-base/tests/compile-and-dump/Singletons/PatternMatching.golden
- singletons-base/tests/compile-and-dump/Singletons/ShowDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/StandaloneDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/T178.golden
- singletons-base/tests/compile-and-dump/Singletons/T190.golden
- singletons-base/tests/compile-and-dump/Singletons/T371.golden
- singletons-th/src/Data/Singletons/TH/CustomStar.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Show.hs
- singletons-th/src/Data/Singletons/TH/Names.hs
- singletons-th/src/Data/Singletons/TH/Partition.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons/CHANGES.md
- singletons/src/Data/Singletons/ShowSing.hs
- singletons/src/Data/Singletons/Sigma.hs
By giving `ShowSing'` a quantified superclass constraint, it becomes possible to derive `Show` instances for singleton types that mention `ShowSing` in the instance context. This is a remarkably backwards-compatible change except for one corner case, which I have documented in the Haddocks for `ShowSing'` in `Data.Singletons.ShowSing`.
Fixes #426, as well as one bullet point of #439.
> Tweak ShowSing' so that Show instances for singletons can be derived

- singletons-base/CHANGES.md
- singletons-base/src/Data/Functor/Const/Singletons.hs
- singletons-base/src/Data/Proxy/Singletons.hs
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T492.hs
Since these are defined in modules where we already define many things by hand, this is straightforward to accomplish. Fixes #492.
> Correct the specificities of SConst{,Sym0,Sym1} and ProxySym0

- README.md
- singletons-base/CHANGES.md
- singletons-base/src/Data/Eq/Singletons.hs
- singletons-base/src/Data/Singletons/Base/Enum.hs
- singletons-base/src/GHC/TypeLits/Singletons.hs
- singletons-base/src/GHC/TypeLits/Singletons/Internal.hs
- singletons-base/src/Text/Show/Singletons.hs
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/ShowDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/T487.golden
- singletons-base/tests/compile-and-dump/Singletons/T487.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Show.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
GHC 9.2 now supports type-level characters, which means that `singletons-th` is now able to promote and single character literals in certain circumstances. It also means that we can remove two terrible hacks in `Text.Show.Singletons`:
* We no longer need `SChar`, which fakes type-level characters with `Symbol`s of length one.
* The `PShow` and `SShow` instances for `Symbol` can now display escape characters properly rather than returning the input `Symbol` unchanged.
Fixes #487.
> Support type-level `Char`s

- README.md
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T480.golden
- singletons-base/tests/compile-and-dump/Singletons/T480.hs
- singletons-base/tests/compile-and-dump/Singletons/T489.golden
- singletons-base/tests/compile-and-dump/Singletons/T489.hs
- singletons-th/CHANGES.md
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Promote/Type.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
While supporting visible type applications in their full generality is challenging, type applications in data constructor patterns are a very well behaved subset, which makes it quite feasible to support in `singletons-th`. This patch accomplishes just that.
We also make an effort to distinguish between wildcard types found in type applications in data constructor, which we can support, and other wildcard types, which we cannot yet support due to GHC restrictions about using wildcard types in kind-level contexts. I have added a section to the `README` to explain this distinction.
Fixes #489.
While I was in town, I also improved the error message that `singletons-th` produces when it tries to promote a wildcard type that it cannot currently support, thus fixing #480.
> `singletons-th`: Support type applications in data constructor patterns 

- singletons/src/Data/Singletons/ShowSing.hs
`(~)` now requires `TypeOperators` in GHC 9.4 (see [the 9.4 Migration Guide](https://gitlab.haskell.org/ghc/ghc/-/wikis/migration/9.4?version_id=503a517b7238e8bac3dd588f32e234bf74b17097#-is-now-a-type-operator)) to build without warnings.
> Adapt to `(~)` becoming a type operator

- singletons-base/CHANGES.md
- singletons-base/singletons-base.cabal
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T536.golden
- singletons-base/tests/compile-and-dump/Singletons/T536.hs
- singletons-th/CHANGES.md
- singletons-th/singletons-th.cabal
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Decide.hs
The code paths for generating `SDecide` and `ShowSing` instances are somewhat
different from the code paths for other derived instances, and while the latter
code paths remembered to call `promoteType` on types that are meant to appear
as kinds, the `SDecide` and `ShowSing` code paths did not remember to do this.
Easily fixed.
> Fix #536 with tactical uses of `promoteType`

- singletons-th/src/Data/Singletons/TH.hs
- singletons/src/Data/Singletons.hs
This PR is a collection of documentation improvements surrounding the `SingI` class (re #260 and #527), as well as the `cases`/`sCases` functions (re #543).
> Improve documentation of `SingI`, `cases`, and `sCases`

- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Monad.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
Previous versions of `singletons` generated uses of `unSingFun*` as a way to accomplish eta expansion. In the current version of the library, however, eta expansion is instead accomplished by giving function clauses more patterns, which removes the need for `unSingFun*` entirely. There were still some vestigial remains of the old `unSingFun*` machinery lying around, however, so this patch removes them.
While I was in the neighborhood, I took the opportunity to document some of the invariants that the current eta expansion machinery relies on.
Fixes #545.
> `singletons-th`: Remove unused `unSingFun*` machinery

- singletons-base/tests/compile-and-dump/GradingClient/Database.golden
- singletons-base/tests/compile-and-dump/InsertionSort/InsertionSortImp.golden
- singletons-base/tests/compile-and-dump/Singletons/CaseExpressions.golden
- singletons-base/tests/compile-and-dump/Singletons/PatternMatching.golden
- singletons-base/tests/compile-and-dump/Singletons/T150.golden
- singletons-base/tests/compile-and-dump/Singletons/T160.golden
- singletons-base/tests/compile-and-dump/Singletons/T183.golden
- singletons-base/tests/compile-and-dump/Singletons/TopLevelPatterns.golden
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Type.hs
Explicit kind annotations aren't necessary in modern `singletons-th` due to the approach that it uses for singling `case` expressions. This allows us to delete a modest amount of code.
Fixes #547.
> `singletons-th`: Remove unneeded kind annotation when singling `case` expressions

- singletons-base/CHANGES.md
- singletons-base/singletons-base.cabal
- singletons-base/src/Data/Singletons/Base/PolyError.hs
- singletons-base/src/GHC/TypeLits/Singletons/Internal.hs
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T89.golden
- singletons-base/tests/compile-and-dump/Singletons/T89.hs
Previously, we had generalized the argument kind to `Error` in commit 077aee54a07f78fbff044a2a4801bfb992a898cf to permit passing things to `Error` besides `Symbol`s. Back then, there was no way to `show` things at the type level, nor was there a way to manipulate `Symbol`s in any meaningful fashion, so this seemed like a reasonable choice.
Nowadays, however, the story is different. There is a type-level `Show_` function, and the API for manipulating `Symbol`s is nearly as expressive as the API for manipulating `String`s.  What's more, making `Error`'s argument kind more general introduces ambiguity-related issues when deriving `Enum` instances with `OverloadedStrings` enabled, as observed in https://github.com/goldfirere/singletons/issues/89.
In light of this, I have changed the API such …
> Monomorphize kinds of `Error{,WithoutStackTrace}`, introduce `PolyError`

- .github/workflows/haskell-ci.yml
- README.md
- cabal.project
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T559.golden
- singletons-base/tests/compile-and-dump/Singletons/T559.hs
- singletons-th/src/Data/Singletons/TH/CustomStar.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Bounded.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Enum.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Eq.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Foldable.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Functor.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Ord.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Show.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Traversable.hs
- singletons-th/src/Data/Singletons/TH/Deriving/Util.hs
- singletons-th/src/Data/Singletons/TH/Partition.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Data.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
`type data` declarations cannot reasonably be given `SingKind` instances, as these only make sense for things that exist at the term level. Whenever we pass a `type data` declaration to the `singletons-th` machinery, we now always omit generation of a `SingKind` instance.
This requires bumping the `th-desugar` commit to bring in the changes from goldfirere/th-desugar#181, which are necessary for determining whether a locally reified data type is actually a `type data` declaration or not.
Fixes #559.
> Support `type data` out of the box

- README.md
- singletons-base/CHANGES.md
- singletons-base/src/Data/Functor/Compose/Singletons.hs
- singletons-base/src/Data/Functor/Product/Singletons.hs
- singletons-base/src/Data/Functor/Sum/Singletons.hs
- singletons-base/src/Data/Proxy/Singletons.hs
- singletons-base/src/Data/Semigroup/Singletons.hs
- singletons-base/tests/compile-and-dump/GradingClient/Database.golden
- singletons-base/tests/compile-and-dump/Singletons/Maybe.golden
- singletons-base/tests/compile-and-dump/Singletons/Nat.golden
- singletons-base/tests/compile-and-dump/Singletons/OrdDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/StandaloneDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/Star.golden
- singletons-base/tests/compile-and-dump/Singletons/T178.golden
- singletons-base/tests/compile-and-dump/Singletons/T187.golden
- singletons-base/tests/compile-and-dump/Singletons/T190.golden
- singletons-base/tests/compile-and-dump/Singletons/T271.golden
- singletons-base/tests/compile-and-dump/Singletons/T536.golden
- singletons-base/tests/compile-and-dump/Singletons/T555.golden
- singletons-th/CHANGES.md
- singletons-th/singletons-th.cabal
- singletons-th/src/Data/Singletons/TH/Partition.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Decide.hs
- singletons-th/src/Data/Singletons/TH/Single/Ord.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
* `singletons-th` now generates `Eq` or `Ord` instances for data types that derive `Eq` or `Ord` instances, respectively.
* `singletons-base` now defines `Eq` and `Ord` instances by hand for types that do not derive their `Eq` instances (e.g., `SProxy`). It also adds derived `Eq` instances for `Sum`, `Product`, and `Compose` (which were lacking them before) to generate `Eq` and `Ord` instances for the corresponding singleton types.
Fixes #561.
> Define `Eq` and `Ord` instances for singleton types

- .github/workflows/haskell-ci.yml
- cabal.project
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T567.golden
- singletons-base/tests/compile-and-dump/Singletons/T567.hs
- singletons-th/CHANGES.md
- singletons-th/src/Data/Singletons/TH/Single/Data.hs
- singletons-th/src/Data/Singletons/TH/Util.hs
Previously, the algorithm for computing a standalone kind signature for a singled data type's standalone kind signature was poorly implemented, and it would combine type variables from the original data type's standalone kind signature alongside type variables from the user-written binders in the data type declaration. The result was that it was possible for `singletons-th` to single a data type and produce a standalone kind signature that was completely ill-scoped, as seen in https://github.com/goldfirere/singletons/issues/567.
This patch implements a new algorithm that is closely based on GHC's `matchUpSigWithDecl` function, which GHC uses to match up type variables from data type SAKS with their user-written binders. While more verbose, the new algorithm is (in my opinion) easier to …
> Prefer user-written binder names in singled data type SAKS

- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T571.golden
- singletons-base/tests/compile-and-dump/Singletons/T571.hs
- singletons-th/CHANGES.md
- singletons-th/src/Data/Singletons/TH/Names.hs
- singletons-th/src/Data/Singletons/TH/Promote/Monad.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Monad.hs
Previously, `SgEnv` (the reader environment for `SgM`, the singling monad) was only tracking let-bound variables.  But as #571 reveals, it must track _lambda_-bound variables as well, lest the `lookupVarE` function accidentally look up a top-level function name instead of a local name that shadows it.
It turns out that `PrEnv` (the reader environment for `PrM`, the promotion monad) was already doing this, so this patch mostly copies the existing `PrM` treatment for lambda-bound variables over to `SgM`. While I was in town, I took the liberty to clean up the naming conventions a bit and document how all of this works in the new `Note [Tracking local variables]` in `Data.Singletons.TH.Promote.Monad`.
Fixes #571.
> Clean up local variable tracking in `SgM`

- .github/workflows/haskell-ci.yml
- cabal.project
- singletons-base/singletons-base.cabal
- singletons-base/tests/compile-and-dump/Promote/T361.golden
- singletons-base/tests/compile-and-dump/Singletons/BoundedDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/T271.golden
- singletons-base/tests/compile-and-dump/Singletons/T296.golden
- singletons-base/tests/compile-and-dump/Singletons/T297.golden
- singletons-base/tests/compile-and-dump/Singletons/T353.golden
- singletons-base/tests/compile-and-dump/Singletons/T371.golden
- singletons-base/tests/compile-and-dump/Singletons/T412.golden
- singletons-base/tests/compile-and-dump/Singletons/T450.golden
- singletons-base/tests/compile-and-dump/Singletons/T567.golden
- singletons-th/singletons-th.cabal
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
This bumps the `th-desugar` submodule to bring in all of the changes in the upcoming `1.16` release. Aside from bumping version bounds, the only other changes that had to be made on the `singletons` side are:
* `singletons-th` now has explicit failure cases for typed TH splices.
* Due to goldfirere/th-desugar#194, desugared data constructors now look like this:
```hs
DataCon :: forall (a :: Type) (b :: Type). DataType a b
```
Instead of this:
```hs
DataCon :: forall (a :: Type) (b :: Type). DataType (a :: Type) (b :: Type)
```
This causes the expected output for some test cases to change, but they are benign changes.
> Bump `th-desugar` submodule to version `1.16`

- .github/workflows/haskell-ci.yml
- README.md
- cabal.haskell-ci
- singletons-base/CHANGES.md
- singletons-base/README.md
- singletons-base/singletons-base.cabal
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/SingletonsBaseTestSuiteUtils.hs
- singletons-base/tests/compile-and-dump/GradingClient/Database.hs
- singletons-base/tests/compile-and-dump/Singletons/T342.golden
- singletons-base/tests/compile-and-dump/Singletons/T342.hs
- singletons-base/tests/compile-and-dump/Singletons/TypeAbstractions.golden
- singletons-base/tests/compile-and-dump/Singletons/TypeAbstractions.hs
- singletons-th/CHANGES.md
- singletons-th/README.md
- singletons-th/singletons-th.cabal
- singletons-th/src/Data/Singletons/TH/Deriving/Bounded.hs
- singletons-th/src/Data/Singletons/TH/Names.hs
- singletons-th/src/Data/Singletons/TH/Options.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Promote/Defun.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Data.hs
- singletons-th/src/Data/Singletons/TH/Single/Fixity.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
- singletons-th/src/Data/Singletons/TH/Util.hs
- singletons/singletons.cabal
- singletons/tests/ByHand2.hs
This:
* Supports invisible binders in type-level declarations.
* Supports the `FldName` namespace introduced in GHC 9.8.
* Tweaks some code to avoid `-Wx-partial` warnings introduced in GHC 9.8.
See also #564.
> `singletons-{th,base}`: Require building with GHC 9.8 

- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T563.golden
- singletons-base/tests/compile-and-dump/Singletons/T563.hs
- singletons-th/CHANGES.md
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Fixity.hs
Now that we have the ability to distinguish the `FldName` namespace from the `VarName` namespace, we can prevent `singletons-th` from promoting or singling the names of records to top-level field selectors when `NoFieldSelectors` is active.
Fixes #563.
> Don't promote/single field selectors with `NoFieldSelectors`

- .github/workflows/haskell-ci.yml
- README.md
- cabal.project
- singletons-base/singletons-base.cabal
- singletons-th/singletons-th.cabal
- singletons-th/src/Data/Singletons/TH/Partition.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Promote/Defun.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Fixity.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
This bumps the `th-desugar` commit in the `cabal.project` file's `source-repository-package` to bring in the changes from `th-desugar-1.17`. Among other things, this version of `th-desugar` adds support for:
* Namespace specifiers in fixity declarations
* Embedded type expressions and patterns
* Invisible type patterns
For now, `singletons-th` will error if it encounters any of these constructs. Where appropriate, I have opened issues to track the idea of supporting these language features in `singletons-th`:
* For namespace specifiers in fixity declarations, see https://github.com/goldfirere/singletons/issues/582.
* Supporting embedded type expressions and patterns seems quite difficult due to `singletons-th`'s policy of only promoting/singling vanilla type signatures (see the `README`), …
> Require building with `th-desugar-1.17`

- .github/workflows/haskell-ci.yml
- cabal.project
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T585.golden
- singletons-base/tests/compile-and-dump/Singletons/T585.hs
- singletons-th/CHANGES.md
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Util.hs
Previously, `promoteLetDecName` would convert every `DTyVarBndrSpec` in an outermost `forall` to an invisible argument in a promoted type family equation. This is not quite right, however, as https://github.com/goldfirere/singletons/issues/585 reveals: we do not want to convert _inferred_ type variable binders to invisible arguments.
To do this properly, we introduce a new `tvbSpecsToBndrVis` function, which converts a list of `DTyVarBndrSpec`s to a list of `DTyVarBndrVis`es, dropping any `DTyVarBndrSpec`s with an `InferredSpec` in the process. We then use `tvbSpecsToBndrVis` in `promoteLetDecName`, which neatly fixes https://github.com/goldfirere/singletons/issues/585.
> `promoteLetDecName`: Fix visibility-related bug

- README.md
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T582.golden
- singletons-base/tests/compile-and-dump/Singletons/T582.hs
- singletons-th/src/Data/Singletons/TH/Partition.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Promote/Defun.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Fixity.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
During promotion, we now give promoted fixity declarations the `type` namespace, and during singling, we now give singled fixity declarations the `type` namespace (if it is a singled class declaration) or the `data` namesapce (for all other singled names). Doing so makes our intentions clearer, and it also future-proofs the code against planned GHC changes discussed in [GHC proposal 65](https://github.com/ghc-proposals/ghc-proposals/blob/8443acc903437cef1a7fbb56de79b6dce77b1a09/proposals/0065-type-infix.rst#migration-plan), where specifier-less fixity declarations (e.g., `infixl 4 %%%`) will become an error if they refer to both a term-level and type-level `%%%` name.
We now also take namespace specifiers into account when promoting fixity declarations. This is because `Wrinkle 1: When …
> Use explicit namespace specifiers when promoting/singling fixity declarations

- singletons-base/src/Data/Foldable/Singletons.hs
- singletons-base/src/Data/Functor/Compose/Singletons.hs
- singletons-base/src/Data/Functor/Const/Singletons.hs
- singletons-base/src/Data/Functor/Product/Singletons.hs
- singletons-base/src/Data/Functor/Sum/Singletons.hs
- singletons-base/src/Data/Proxy/Singletons.hs
- singletons-base/src/Data/Singletons/Base/TypeError.hs
- singletons-base/src/Data/Traversable/Singletons.hs
- singletons-base/src/GHC/TypeLits/Singletons/Internal.hs
- singletons-th/src/Data/Singletons/TH/CustomStar.hs
- singletons/src/Data/Singletons.hs
- singletons/src/Data/Singletons/Sigma.hs
- singletons/tests/ByHand.hs
- singletons/tests/ByHand2.hs
This makes it clearer what the `Sing` instances are actually matching on. Moreover, this will be required in order to make these instances compile after [GHC#23515](https://gitlab.haskell.org/ghc/ghc/-/issues/23515) is implemented.
This resolves the "`Sing` instances without explicit left-hand sides" section of #601.
> Make `Sing` instances more explicit on their left-hand sides

- singletons-base/CHANGES.md
- singletons-base/src/Data/Functor/Compose/Singletons.hs
Previously, the promoted versions of certain `Compose` instances (`Functor`, `Foldable`, etc.) would be overly general due to the fact that `singletons-th` omits instance contexts during promotion. For example, the promoted `Functor` instance for `Compose` was:
```hs
instance PFunctor (Compose (f :: k -> Type) (g :: Type -> k)) where ...
```
But this was too general, as `f` and `g` should both be of kind `Type -> Type` instead. The defunctionalization symbols associated with the instances also had a similar problem.
This patch annotates each instance with an explicit kind (e.g., `Functor (Compose (f :: Type -> Type) g)` to ensure that the promoted instances also have the intended kind. This is very much in the same spirit as the situation described in `Note [Using standalone kind …
> Give `Compose`'s instances explicit kind signatures

- singletons-base/CHANGES.md
- singletons-base/src/Data/Foldable/Singletons.hs
- singletons-base/src/Data/Functor/Product/Singletons.hs
This adds more explicit `Type -> Type` kind signatures to definitions that would otherwise be kind-generalized to have overly polymorphic kinds:
* The kinds of `Asum` and `Msum` (the promoted counterparts to the term-level `asum` and `msum` functions, respectively).
* The helper type families generated when promoting the `Alternative` and `MonadPlus` instances for `Data.Functor.Product`. This sort of kind polymorphism isn't observable by users in today's GHC, but it will cause problems later in a future version of GHC that implements [GHC#23515](https://gitlab.haskell.org/ghc/ghc/-/issues/23515). (See #601.)
(I should have added these as part of #606 or #607, but I forgot them due to an oversight.)
> Give `asum`, `msum`, and `Product` instances explicit kind signatures

- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Promote/T613.golden
- singletons-base/tests/compile-and-dump/Promote/T613.hs
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Promote/Monad.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Syntax.hs
- singletons-th/src/Data/Singletons/TH/Syntax/LocalVar.hs
- singletons-th/src/Data/Singletons/TH/Util.hs
Doing so makes it possible to track the kinds of scoped type variables with greater precision during lambda lifting. See the golden output for the new `T613` test case to see an example of this in action.
Fixes https://github.com/goldfirere/singletons/issues/613.
> `singletons-th`: Make `pr_scoped_vars` a list of `LocalVar`s, not `Name`s

- .github/workflows/haskell-ci.yml
- cabal.project
- singletons-base/tests/compile-and-dump/Promote/T361.golden
- singletons-base/tests/compile-and-dump/Singletons/T353.golden
- singletons-base/tests/compile-and-dump/Singletons/T567.golden
- singletons-base/tests/compile-and-dump/Singletons/TypeAbstractions.golden
- singletons-th/CHANGES.md
- singletons-th/src/Data/Singletons/TH/Promote.hs
- singletons-th/src/Data/Singletons/TH/Promote/Defun.hs
- singletons-th/src/Data/Singletons/TH/Single.hs
- singletons-th/src/Data/Singletons/TH/Single/Data.hs
- singletons-th/src/Data/Singletons/TH/Util.hs
This patch adapts to the changes in goldfirere/th-desugar#227:
* As part of a fix for https://github.com/goldfirere/th-desugar/issues/223, https://github.com/goldfirere/th-desugar/pull/227 adds its own version of `singletons-th`'s `matchUpSAKWithDecl` function (now called `dMatchUpSAKWithDecl` on the `th-desugar` side). This PR completes the migration by removing `singletons-th`'s version of `matchUpSAKWithDecl` and instead using the version offered by `th-desugar`.
* As part of a fix for https://github.com/goldfirere/th-desugar/issues/199 and https://github.com/goldfirere/th-desugar/issues/220, https://github.com/goldfirere/th-desugar/pull/227 improves `th-desugar`'s ability to locally reify and desugar precise types for Haskell98-style data constructors and class methods. This has a …
> Adapt to goldfirere/th-desugar#227

- README.md
- singletons-base/src/Data/Functor/Compose/Singletons.hs
- singletons-base/src/Data/Functor/Const/Singletons.hs
- singletons-base/src/Data/Functor/Product/Singletons.hs
- singletons-base/src/Data/Functor/Sum/Singletons.hs
- singletons-base/src/Data/Proxy/Singletons.hs
- singletons-base/tests/SingletonsBaseTestSuite.hs
- singletons-base/tests/compile-and-dump/Singletons/T565.golden
- singletons-base/tests/compile-and-dump/Singletons/T565.hs
- singletons-th/src/Data/Singletons/TH/Single/Data.hs
- singletons-th/src/Data/Singletons/TH/Single/Type.hs
Now that https://github.com/goldfirere/th-desugar/issues/199 has been fixed, `singletons-th` can always guarantee that the type variable specificities that it reifies will be accurate. As such, all of wrinkle 2 in `Note [Preserve the order of type variables during singling]` is moot, so this PR deletes this wrinkle entirely. Wrinkle 3 has now been renamed to wrinkle 2.
What was formerly known as wrinkle 3 is mostly kept the same, although I have expanded upon it a little to clarify what we single data constructors such as `Nothing :: forall a. Maybe a` to `SNothing :: forall a. SMaybe (Nothing :: Maybe a)` rather than, say, `SNothing :: forall a. SMaybe (Nothing @a)`. For instance, imagine if `a` was inferred rather than specified!
I have added a `T565` test case which ensures that …
> Remove wrinkle 2 (and revise wrinkle 3) of `Note [Preserve the order of type variables during singling]`

- .github/workflows/haskell-ci.yml
- README.md
- cabal.haskell-ci
- github.yml.patch
- singletons-base-code-generator/singletons-base-code-generator.cabal
- singletons-base/CHANGES.md
- singletons-base/README.md
- singletons-base/singletons-base.cabal
- singletons-base/tests/compile-and-dump/Singletons/Classes.golden
- singletons-base/tests/compile-and-dump/Singletons/Fixity.golden
- singletons-base/tests/compile-and-dump/Singletons/ShowDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/StandaloneDeriving.golden
- singletons-base/tests/compile-and-dump/Singletons/T159.golden
- singletons-base/tests/compile-and-dump/Singletons/T197.golden
- singletons-base/tests/compile-and-dump/Singletons/T197b.golden
- singletons-base/tests/compile-and-dump/Singletons/T322.golden
- singletons-base/tests/compile-and-dump/Singletons/T326.golden
- singletons-base/tests/compile-and-dump/Singletons/T412.golden
- singletons-base/tests/compile-and-dump/Singletons/T582.golden
- singletons-th/CHANGES.md
- singletons-th/README.md
- singletons-th/singletons-th.cabal
- singletons/CHANGES.md
- singletons/singletons.cabal
The most notable change is that because GHC 9.12 includes a fix for https://gitlab.haskell.org/ghc/ghc/-/issues/24911, the test suite output now includes explicit namespaces for its fixity declarations. Aside from that, the changes here are mostly bumping upper version bounds.
Checks off one box in https://github.com/goldfirere/singletons/issues/619.
> `singletons-{th,base}`: Require building with GHC 9.12
