goldfirere/singletons

src/Data/Singletons.hs
tests/SingletonsTestSuite.hs
tests/compile-and-dump/Singletons/T153.hs

Explicit forall in withSomeSing

---

singletons.cabal
src/Data/Singletons/Prelude/Instances.hs
src/Data/Singletons/Single.hs
src/Data/Singletons/Single/Data.hs
src/Data/Singletons/Single/Fixity.hs
tests/SingletonsTestSuite.hs
tests/compile-and-dump/Singletons/T159.ghc80.template
tests/compile-and-dump/Singletons/T159.hs

Auto-generate infix declarations

---

src/Data/Singletons/Prelude/Function.hs
src/Data/Singletons/Prelude/List/NonEmpty.hs
src/Data/Singletons/Prelude/Ord.hs

On my machine, using ghc-8.2.0.20170522, I was getting many:
"Haddock documentation not (yet) handled by Template Haskell"
Maybe it's my machine/config?

Fix haddock failures for TH splices

---

src/Data/Singletons/Single.hs
src/Data/Singletons/Single/Data.hs
tests/SingletonsTestSuite.hs
tests/SingletonsTestSuiteUtils.hs
tests/compile-and-dump/GradingClient/Database.ghc82.template
tests/compile-and-dump/InsertionSort/InsertionSortImp.ghc82.template
tests/compile-and-dump/Singletons/AsPattern.ghc82.template
tests/compile-and-dump/Singletons/BoundedDeriving.ghc82.template
tests/compile-and-dump/Singletons/BoxUnBox.ghc82.template
tests/compile-and-dump/Singletons/Classes.ghc82.template
tests/compile-and-dump/Singletons/Classes2.ghc82.template
tests/compile-and-dump/Singletons/DataValues.ghc82.template
tests/compile-and-dump/Singletons/EnumDeriving.ghc82.template
tests/compile-and-dump/Singletons/HigherOrder.ghc82.template
tests/compile-and-dump/Singletons/Lambdas.ghc82.template
tests/compile-and-dump/Singletons/Maybe.ghc82.template
tests/compile-and-dump/Singletons/Nat.ghc82.template
tests/compile-and-dump/Singletons/Operators.ghc82.template
tests/compile-and-dump/Singletons/OrdDeriving.ghc82.template
tests/compile-and-dump/Singletons/PatternMatching.ghc82.template
tests/compile-and-dump/Singletons/Records.ghc82.template
tests/compile-and-dump/Singletons/ShowDeriving.ghc82.template
tests/compile-and-dump/Singletons/StandaloneDeriving.ghc82.template
tests/compile-and-dump/Singletons/Star.ghc82.template
tests/compile-and-dump/Singletons/T159.ghc82.template
tests/compile-and-dump/Singletons/T178.ghc82.template
tests/compile-and-dump/Singletons/T206.hs
tests/compile-and-dump/Singletons/TopLevelPatterns.ghc82.template

This ended up being much simpler than I thought - essentially, it amounts to changing two lines in `Data.Singletons.Single`! The rest of the changes in this PR percolate up from that.
Fixes #206.

Generate Sing instances using GADTs instead of ExistentialQuantification

---

CHANGES.md
README.md
src/Data/Singletons/Partition.hs
src/Data/Singletons/Util.hs
tests/SingletonsTestSuite.hs
tests/compile-and-dump/Singletons/T209.ghc82.template
tests/compile-and-dump/Singletons/T209.hs

Includes an addendum to the `README` describing how this whole shindig works.
Fixes #209.

Implement DeriveAnyClass

---

CHANGES.md
src/Data/Singletons.hs
src/Data/Singletons/Internal.hs
src/Data/Singletons/Prelude/Num.hs
src/Data/Singletons/TypeLits/Internal.hs

Change Demote Nat to Natural

---

CHANGES.md
src/Data/Singletons/Internal.hs

Implement toSing in the SingKind (k1 ~> k2) instance

---

CHANGES.md
src/Data/Singletons.hs
src/Data/Singletons/Internal.hs

Solves the original question of #273.

Added SingI pattern synonym.

---

CHANGES.md
src/Data/Singletons.hs
src/Data/Singletons/Internal.hs

From #273
```haskell
pattern AsSing :: SingKind k => forall (a :: k). Sing a -> Demote k
pattern AsSing sing <- ((\demote -> withSomeSing demote SomeSing) -> SomeSing sing)
where AsSing sing = fromSing sing 
```

Added AsSing and documentation.

---

src/Data/Singletons/CustomStar.hs
src/Data/Singletons/Promote.hs
src/Data/Singletons/Single.hs
tests/SingletonsTestSuite.hs
tests/compile-and-dump/Singletons/T342.ghc84.template
tests/compile-and-dump/Singletons/T342.hs

While I was in town, I replaced every use of `reifyWithWarning` with `reifyWithLocals`.

Fix #342 by using reifyWithLocals in more places

---

CHANGES.md
README.md
src/Data/Singletons.hs
src/Data/Singletons/Prelude/Monoid.hs
src/Data/Singletons/Prelude/Semigroup.hs
src/Data/Singletons/ShowSing.hs
tests/SingletonsTestSuite.hs
tests/SingletonsTestSuiteUtils.hs
tests/compile-and-dump/Singletons/T371.ghc86.template
tests/compile-and-dump/Singletons/T371.hs

See the discussion on #371 for why this is necessary.

Fix #371 by making ShowSing a class again

---

CHANGES.md
src/Data/Singletons/Promote.hs
tests/SingletonsTestSuite.hs
tests/compile-and-dump/Singletons/T376.ghc86.template
tests/compile-and-dump/Singletons/T376.hs

When code golfing, sometimes you get a bogey. Other times, you get a hole-in-one. This is one of those times.

Fix #376 by inserting an apostrophe

---

README.md

Previously, the only mention of how to do so in the `README` was a simple link to #76. But finding the relevant information in #76 requires digging through several comments, and to make things worse, the actual advice (in https://github.com/goldfirere/singletons/issues/76#issuecomment-44220892) has bitrotted!
This patch (1) cleans up the bitrot, and (2) enshrines the advice in the `README` itself, where it belongs.
Fixes #76 (again).

More thoroughly document how to work with datatypes that use arrows/literals

---

README.md
singletons-base/tests/SingletonsBaseTestSuite.hs
singletons-base/tests/compile-and-dump/Singletons/T470.golden
singletons-base/tests/compile-and-dump/Singletons/T470.hs
singletons-th/CHANGES.md
singletons-th/src/Data/Singletons/TH/Single/Data.hs

Preserve strict data type fields when singling

---

singletons-base/CHANGES.md
singletons-base/singletons-base.cabal
singletons-base/src/Data/Functor/Compose/Singletons.hs
singletons-base/src/Data/Functor/Product/Singletons.hs
singletons-base/src/Data/Functor/Sum/Singletons.hs

Add Data.Functor.{Compose,Product,Sum}.Singletons

---

README.md

While working on #487, I realized that the current `README` documentation about literal patterns is non-existent, so I decided to add some. In order to explain the limitations of literal patterns, however, one must explain the limitations of overlapping patterns, and I discovered that the `README` also doesn't do a very good job of explaining this either. At this point, I decided to spin off this documentation improvement into its own commit.

Add more documentation for overlapping and literal patterns

---

README.md
singletons-base/tests/SingletonsBaseTestSuite.hs
singletons-base/tests/compile-and-dump/Singletons/T511.golden
singletons-base/tests/compile-and-dump/Singletons/T511.hs
singletons-th/src/Data/Singletons/TH/Promote/Type.hs

Provide more specific error message for partial `(->)` applications

---

README.md

Fix links to papers in README.

---

singletons-base/README.md
singletons-base/singletons-base.cabal
singletons-th/README.md
singletons-th/singletons-th.cabal
singletons/README.md
singletons/singletons.cabal
singletons/src/Data/Singletons.hs

This follows on the heels of #516. Fixes #517.

Update all `singletons` paper links to richarde.dev

---

singletons/src/Data/Singletons.hs

Instead of `unsafeCoerce`, we can use the more recent `withDict` primitive from `GHC.Exts`. Among other benefits, this is more likely to be future-proof against possible changes to GHC's representation of "newtype classes" in the future.
Fixes #490.

Use `withDict` to implement `withSingI` on recent GHCs

---

singletons-base/tests/SingletonsBaseTestSuiteUtils.hs

Normalize Windows-style path separators

---

singletons-th/CHANGES.md
singletons-th/singletons-th.cabal
singletons-th/src/Data/Singletons/TH/Single/Monad.hs
singletons-th/src/Data/Singletons/TH/Util.hs

`singletons-th`: Allow building with `mtl-2.3.*`

---

singletons-th/src/Data/Singletons/TH/Single.hs

This `ctxt` argument is dead code, as explained in the comment that I have added next to the call to `singLetDecRHS` in `singInstD`.
Fixes #551.

Delete unnecessary `ctxt` argument in `singInstD`
